### ISSUE TITLE
Tab Options Not There

### ISSUE THREAD

**Issue by lwb52** [benji300/joplin-note-tabs#14]
There is no [longer] menu item for `Tools›Options›Note¬Tabs`—all that exists in JopV1.5.12 is `Tools›Tabs›{several available actions}`.
What options can be chosen (still), and how?

**Comment by benji300** [comment]
Could you please try it with Joplin v1.5.14. Because I cannot reproduce this behavior on my side.
Which version did you installed? Pre-built v0.1.0? Because I'm currently working on v1.0.0 and the master branch might be a bit messy...

**Comment by benji300** [comment]
Now I know what your problem was/is. There has never been a `Tools>Options>Note Tabs` menu item. What you are looking for are the plugin settings, which you can find in the general settings view of the app. When you open it (`CmdOrCtrl+,`) you will find the tab **Note Tabs** on the left side. There you will find all the settings for the plugin.
