### ISSUE TITLE
Add toggle button to show/hide the "Note Tab" bar

### ISSUE THREAD

**Issue by soorajsprakash** [benji300/joplin-note-tabs#37]
Using [Note list and sidebar toggle buttons v1.0.3](https://github.com/laurent22/joplin/tree/dev/packages/plugins/ToggleSidebars) 
Just like this, can you get a toggle button?

## Use case:
* When using split screen, referring websites, pdf and making notes in Joplin, If the Pinned Tabs Bar is shown, the area to take note is very low, so it would be better if we have a toggle button.
* * *
* Example for showing split screen.
![Screenshot from 2021-02-11 19-35-50](https://user-images.githubusercontent.com/26853789/107646916-8b25a780-6ca0-11eb-80d6-1ee505ce689d.png)
* * *
* Example pic showing toggled state , but Pinned tab is making toggled tabs useless, cos no space is saved.(top right there is toggle to hide those 2 tabs)
![Screenshot from 2021-02-11 19-36-01](https://user-images.githubusercontent.com/26853789/107647179-e0fa4f80-6ca0-11eb-8653-b300e9d21178.png)
)

**Comment by benji300** [comment]
There is already the command `tabsToggleVisibility` to which a keyboard shortcut can be assigned. I wouldn't add this additional button yet, because I don't think it would help many users, but rather disturb them. So I would wait if this feature will be requested more often before I add it to the plugin.

**Comment by soorajsprakash** [comment]
oh, thats nice & helpfull. Didn't knew the command. So I'm closing the issue. Good work with the pluggin. Thanks
