### ISSUE TITLE
last tab not removed, and more

### ISSUE THREAD

**Issue by ajay-gh** [benji300/joplin-note-tabs#44]
I like the idea.
Now, imagine you have added 3 notes to the tabs, and you decide to remove them one by one. So you click on the last note's little x on the right. And it's removed. You click to remove the 2nd, but ups, it just changes from black text to gray. And the third does go away at all. There is something wrong with the processing of the list of "tabbed" notes. 
I tried to uninstall and reinstall the plugin. Not only is the problem not solved, but the previosly tabbed notes come back, as if removing the plugin didn't remove all related information. That is not acceptable.

**Comment by benji300** [comment]
This is not a problem in the implementation of the plugin but a intended behavior. 

Background:
The Note Tabs plugin always reflects the selected note, i.e. the current selected note is always displayed as a tab. As it is the case with most apps with tabs. Since there is almost always a note selected in Joplin, the plugin will also always display a tab. Regardless of whether the tab was closed in the last session. That's why the last tab can never be removed as their will always be a note selected at this point of time.

But that is just as intended and I would not know how the behavior should be otherwise.

If this behavior is "not acceptable" for you, you could test the Favorites plugin. You could also use this as a "tabs" plugin. Whereby the displayed "tabs" would be freely selectable by you.

**Comment by ajay-gh** [comment]
Didn't mean to upset the dev by using the word "unacceptable" - as I said, I like the plugin. 
What I meant is that the plugin's record doesn't get cleaned up when removing it. Whether this is really the plugin's fault or Joplin's doing. Anyway, I see now your point about why one note would always remain. Thanks for the clarification. All the Best !

**Comment by benji300** [comment]
Ah sorry... I think there was a little misunderstanding on my side...

Regarding "_What I meant is that the plugin's record doesn't get cleaned up when removing it_" - this is currently a limitation of the app itself. It doesn't cleanup the settings table in the database once a plugin is removed. Also there's no way to do this from the plugin itself. So if you remove the plugin with still existing tabs, they will reappear (if the notes still exist) when you install the plugin again.
But I don't know whether or not this was already reported to the app devs.
