### ISSUE TITLE
Background color drags too far down

### ISSUE THREAD

**Issue by Luekuu** [benji300/joplin-note-tabs#51]
Hii 

Is it possible to customize the background so that it only appears at the top of the tabs? I made the color extra to white so you can see it. 

https://i.imgur.com/wGlPsSR.png

Thanks for developing this nice plugin!
Best Regards, Lüku

**Comment by benji300** [comment]
Hi @Luekuu,

this was an issue of the App itself and not related to the plugin. But it is already fixed in latest App release v2.2.7.
Please see on the forum https://discourse.joplinapp.org/t/plugin-note-tabs/12752/200 and following posts.

Please always check the forum before adding tickets here...
I will close this ticket.

Thanks,
Benji

**Comment by Luekuu** [comment]
ohh sorry.. 
Thanks you! Regrads, Lüku
